# Generated by Django 3.2.13 on 2022-11-03 11:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221103_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_sm',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
