# Generated by Django 3.2.13 on 2022-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/', max_length=100),
        ),
    ]
