# Generated by Django 3.2.13 on 2022-11-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221106_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
